### ISSUE TITLE
Deprecation: BiquadFilterNode.frequency.value

### ISSUE THREAD

**Issue by DannyBen** [kevincennis/TinyMusic#15]
Getting this warning in the Chrome when running the "Getting Started" code:

```
TinyMusic.js:94 [Deprecation] BiquadFilterNode.frequency.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
(anonymous) @ TinyMusic.js:94
Sequence.createFxNodes @ TinyMusic.js:91
Sequence @ TinyMusic.js:78
```

**Comment by kevincennis** [comment]
Yeah. That looks worse than it is.

TinyMusic doesn't actually rely on the "dezippering" mentioned [here](https://www.chromestatus.com/features/5287995770929152), so there's actually no change needed. The deprecation warning is basically "if you were relying on this undocumented 'dezippering' in order to achieve a ramp in gain, you need to switch to a method that explicitly does that".

TinyMusic (and the code samples in the README) are just setting initial values, which should take effect immediately.

In short, you can ignore those deprecation warnings. They're not actually changing the API, they're simply removing a hidden, undocumented behavior that TinyMusic never used anyway.

If you _really_ hate seeing them, you can switch to `setValueAtTime()` / `setTargetAtTime()` (where the first argument is value, and the second argument is time, which would be `0` for immediate) and the deprecation warnings will go away. Or you can wait until Chrome actually deprecates it, and they'll remove the warnings at that point, too.

**Comment by Cypher1** [comment]
Thanks
